python ../code/depthsizer.py dochtml newlog

python ../code/depthsizer.py --description | sed 's/^/# /' > ../DepthSizer.md
echo >> ../DepthSizer.md

echo '```' >> ../DepthSizer.md
python ../code/depthsizer.py --details >> ../DepthSizer.md
echo '```' >> ../DepthSizer.md
echo >> ../DepthSizer.md
echo 'For a better rendering and navigation of this document, please download and open [`./docs/depthsizer.docs.html`](./docs/depthsizer.docs.html), or visit <https://slimsuite.github.io/depthsizer/>.' >> ../DepthSizer.md
echo 'Documentation can also be generated by running DepthSizer with the `dochtml=T` option. (R and pandoc must be installed - see below.)' >> ../DepthSizer.md
echo >> ../DepthSizer.md
echo '## Introduction' >> ../DepthSizer.md
echo >> ../DepthSizer.md
grep -A 10000 Diploidocus depthsizer.docs.Rmd >> ../DepthSizer.md

cp depthsizer.docs.html ../index.html
cp ../DepthSizer.md ../README.md
